imports:
    - { resource: services/caster.yml }
    - { resource: services/container.yml }
    - { resource: services/parser.yml }
    - { resource: services/resolver.yml }

services:
    knp_rad_resource_resolver.event_listener.resources_listener:
        class: Knp\Rad\ResourceResolver\EventListener\ResourcesListener
        arguments:
            - @knp_rad_resource_resolver.parser.container
            - @knp_rad_resource_resolver.caster.container
            - @knp_rad_resource_resolver.resolver.container
            - @knp_rad_resource_resolver.resource.container
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: resolveResources }
