parameters:
    knp_rad_resource_resolver.caster.container.class:       Knp\Rad\ResourceResolver\Caster\Container
    knp_rad_resource_resolver.caster.array_caster.class:    Knp\Rad\ResourceResolver\Caster\ArrayCaster
    knp_rad_resource_resolver.caster.resource_caster.class: Knp\Rad\ResourceResolver\Caster\ResourceCaster
    knp_rad_resource_resolver.caster.service_caster.class:  Knp\Rad\ResourceResolver\Caster\ServiceCaster
    knp_rad_resource_resolver.caster.variable_caster.class: Knp\Rad\ResourceResolver\Caster\VariableCaster

services:
    knp_rad_resource_resolver.caster.container:
        class: %knp_rad_resource_resolver.caster.container.class%

    knp_rad_resource_resolver.caster.array_caster:
        class: %knp_rad_resource_resolver.caster.array_caster.class%
        public: false
        arguments: [ @knp_rad_resource_resolver.caster.container ]
        tags:
            - { name: knp_rad_resource_resolver.caster }

    knp_rad_resource_resolver.caster.resource_caster:
        class: %knp_rad_resource_resolver.caster.resource_caster.class%
        public: false
        arguments: [ @knp_rad_resource_resolver.resource.container ]
        tags:
          - { name: knp_rad_resource_resolver.caster }

    knp_rad_resource_resolver.caster.service_caster:
        class: %knp_rad_resource_resolver.caster.service_caster.class%
        public: false
        arguments: [ @service_container ]
        tags:
            - { name: knp_rad_resource_resolver.caster }

    knp_rad_resource_resolver.caster.variable_caster:
        class: %knp_rad_resource_resolver.caster.variable_caster.class%
        public: false
        arguments: [ @request_stack ]
        tags:
            - { name: knp_rad_resource_resolver.caster }
